#### a new change
### change made directly on github
### 2nd change made
### 3rd changes made
---
- hosts: all
  become: yes
  tasks:
      - name: Installing apache in remote
        yum: name=httpd state=latest
